columns:
    - case_id: category
    - continent: category
    - education-of_employees: category
    - has_job_experience: category
    - requires_job_training: category
    - no_of_employees: int
    - yr_of_estab: int
    - regtion_of_emplyement: int
    - prevailing_wage: int
    - unit_of_wage: category
    - full_time_position: category
    - case_status: category

numerical_columnn:
    - no_of_employees
    - prevailing_wage
    - yr_of_estab

categorical_column:
      - continent
      - education-of_employees
      - has_job_experience
      - requires_job_training
      - unit_of_wage
      - full_time_position
      - case_status
      - case_id
      - region_of_employment

drop_columns:
    - case_id
    - yr_of_estab

num_features:
    - has_job_ecperience
    - requires_job_training
    - fulll_time_position
    - education_of_employee

oh_columns:
    - continent
    - unit_of_wage
    - region_of_employment

transform_columns:
    - no_of_employees
    - company_age


